### ISSUE TITLE
required properties of multipart/form-data not supported

### ISSUE THREAD

**Issue by thurt** [byu-oit/openapi-enforcer-middleware#10]
I am getting an unexpected validation error with `multipart/form-data` content-type. It appears the middleware is not properly identifying the `picture` property within the `multipart/form-data` request. 

Openapi endpoint
```yaml
  /users/picture:
    put:
      summary: Set user's picture
      operationId: setUserPicture
      x-controller: users
      x-operation: setUserPicture
      tags:
        - Users
      security:
        - bearerAuth: []
      requestBody:
        description: Picture data that is one of gif, jpeg, png
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                picture:
                  type: string
                  format: binary
              required:
                - picture
      responses:
        200:
          description: OK
        401:
          description: Unauthorized
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/AuthError"
```

Running result:
<img width="1254" alt="Screen Shot 2019-05-06 at 12 03 58 PM" src="https://user-images.githubusercontent.com/8955144/57238410-54186180-6ff7-11e9-864b-0df8c913dbf9.png">

**Comment by Gi60s** [comment]
I can confirm that this bug exists. I'll take a look at it today. Thanks.

**Comment by Gi60s** [comment]
Are you using a particular body parser for your `multipart/form-data`?

**Comment by thurt** [comment]
good idea, thanks for checking. 

I am using `multer` express middleware. I didn't expect it to be an issue because I was thinking the openapi-enforcer-middleware would run before the multer middleware does? I have the multer middleware installed on just the endpoint/operation code whereas I have the openapi-enforcer-middleware installed at the top-level of the app: `app.use(enforcer.middleware())`

here is the relevant code that uses multer:
```
const multer = require("multer");

const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 200000 }
});

// set user's picture
const setUserPicture = [
  authMiddleware,
  upload.single("picture"),
  async (req, res) => {
    const supportedContentTypes = ["image/gif", "image/jpeg", "image/png"];
    const { buffer, mimetype } = req.file;
    const { id } = req.user;

    if (!supportedContentTypes.includes(mimetype)) {
      res.status(415).send();
      return;
    }

    try {
      await User.scope("picture").update(
        { picture: buffer, pictureContentType: mimetype },
        { where: { id } }
      );
      res.set({ "Content-Location": `/users/${id}/picture` });
      res.send();
    } catch (err) {
      console.log(err);
      res.status(500).send();
    }
  }
];
```

**Comment by Gi60s** [comment]
The enforcer middleware validates the incoming request prior to calling your controller functions, so by not having parsed the body prior to calling the enforcer middleware we run into the error that it believes the `picture` was never sent.

I have an idea of how to make this work that will probably be functional tomorrow (Tuesday).

**Comment by Gi60s** [comment]
I created an NPM package called [openapi-enforcer-multer](https://www.npmjs.com/package/openapi-enforcer-multer) that should solve this problem for you.

Tackling file uploads for the openapi-enforcer-middleware has been on my to do list for a while, so this was an opportunity to do that.

Check out those docs and let me know if you have any questions. Thanks.

**Comment by thurt** [comment]
can you add openapi-enforcer-multer as a github repo? on npm, there is no link to a github repo

**Comment by thurt** [comment]
there are a couple issues id like to post there if you can create a repo for it

**Comment by Gi60s** [comment]
Yes, I can do that. Thanks for the reminder. I need to get approval to make it public, but that usually happens pretty fast.

**Comment by Gi60s** [comment]
It is now public: https://github.com/byu-oit/openapi-enforcer-multer
