### ISSUE TITLE
Use URL instead of x-controller and x-operation? 

### ISSUE THREAD

**Issue by philsturgeon** [byu-oit/openapi-enforcer-middleware#19]
I'm not sure why you need to add x-controller and x-operation throughout the OpenAPI description document, when you could look up the path in the URL and match on that? 

Seems like it's 

1. placing a lot of burden on the OpenAPI authors 
2. non standard 
3. not portable

**Comment by philsturgeon** [comment]
Also a suggestion, update "Open API" to "OpenAPI" (its currently incorrect), and "OAS" to "OpenAPI" (better for SEO and readability).

**Comment by Gi60s** [comment]
Hey Phil,

Thanks for the suggestions on the SEO improvements. I'll work on getting those implemented. As for your first comment, I'm not sure if I understand exactly what is being said.

The `x-controller` and `x-operation` are used to tell the middleware which file and function to execute. The URL provided in the OpenAPI document is used to find the operation that is being called but then the middleware needs to know which function to route the request to.

This is documented in more detail here: https://byu-oit.github.io/openapi-enforcer-middleware/getting-started#setup

Am I misunderstanding the first comment?

**Comment by Gi60s** [comment]
I've closed this issue for now. I happy to reopen it with more input. I believe the library is currently set up to be as efficient as possible for developers who are looking to link code to OpenAPI documents.

**Comment by philsturgeon** [comment]
Maybe I am missing something, but why do you need to specify the controller and method, when both the JS middleware and the OpenAPI already define a path? You can use the path 

```yaml
paths:
  /foo:
    get:
      ...
```

When somebody hits `GET /foo` then... tadaa! Why do I need to specify the controller and action when that should just work? 

There is a really great ruby implementation that works this way: https://github.com/interagent/committee

**Comment by Gi60s** [comment]
I wish I knew some Ruby to help me understand where we're not connecting here. It is true that an incoming request can easily be mapped to the [Operation](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#operationObject) in the Open API document.

This middleware does the following for each request:
1. Receives the incoming request
2. Identifies which OpenAPI Operation matches the incoming request
3. Deserializes the request
4. Validates the request inputs
5. Passes the request to a function defined by the API developer. (This function handles the validated request and sends a response.)
6. Validates the response.
7. Serializes the response.

So for step 5 (which is where we're talking I believe) the middleware has to know where that function exists so that it can pass the request on. The current model looks at the `x-controller` and `x-operation` to identify that function.

**Comment by philsturgeon** [comment]
Does the middleware have to know that the controller and operation exist? That's not really how middleware works in Rack and its not how middleware works in PHP land either. Maybe this one will read better: https://github.com/thephpleague/openapi-psr7-validator

Basically, the middleware does the OpenAPI lookup and rejects anything coming in for that operation with a body and parameters that do not match. Then if there is a success it simply lets the middleware continue walking on, and the routing mechanism directs the request to the controller and action as normal. 

I've worked with a lot of these middleware systems and yours seems to be the only one needing the user to specify the controller and action.

**Comment by Gi60s** [comment]
OK, I think I'm starting to understand here, so I'm going to take another shot.

My PHP is pretty rusty, but PHP and JavaScript have different execution models. PHP runs a new thread for each request and runs the code linearly. JavaScript has a single constantly running thread that uses sub threads creating both a linear and non-linear paradigm.

The callback paradigm is how Node uses middleware and that is why this library wants to know what function to run for each operation.

One possible way to make this run a bit more like PHP would be to enforce a rigid file structure where the file structure somehow resembled the paths of the OpenAPI document, but that is not the practice used with Node.

Anyway, I could still be way off base here, but maybe that is what you're talking about?

**Comment by philsturgeon** [comment]
Way off, sorry. I’ve built middleware for express and fastify so I’m completely aware of how middleware works in JS. I was giving you the ruby and PHP examples as two other well built middlewares for OpenAPI. Their middleware stacks are all pretty much identical, php and ruby do not have relevant differences when it comes to threads and callbacks in these middleware stacks. 

Let’s stick to express:

https://github.com/Zooz/express-ajv-swagger-validation

Here you can see they use a generic middleware and pass it into every route. That should be possible, and a route level middleware should also be possible so it can be tied to all routes at once:

https://expressjs.com/en/guide/using-middleware.html

Notice that they do this without making people modify their OpenAPI specs. 

Operation method+path, and express route are enough glue for what the request is & should be, without needing to add a third thing.

**Comment by Gi60s** [comment]
OK, finally I think I understand. This middleware does not ask for you to specify in JavaScript the method and path and the callback to call.

If you look at the [intro example in the documentation](https://byu-oit.github.io/openapi-enforcer-middleware/guide/server#example) you'll see that no routes are defined in JavaScript. The OpenAPI document is the one that links routes to callbacks. The middleware itself handles all routes.

Now that you've pointed this out I find it a bit interesting that I never thought of the approach you've brought up. I suppose if you're interested in that approach it would be pretty easy to add.

What do you think, do you prefer the approach that you've mentioned?

**Comment by philsturgeon** [comment]
Express has routes so not using them seems like a bit of a waste though, right? In general relying on routes and operations to find each other means not leaking internal implementation details into the OpenAPI description document, which is public. End users don't care what you called your functions internally, and developers dont want to lose time writing that stuff up when they don't need to. :)

In general I think the JS community has spent a lot of time rewriting the same stuff over and over. I just got 3 people in the PHP community to [agree to merge their openapi middlewares](https://github.com/lezhnev74/openapi-psr7-validator/issues/65) and I wonder if we could do the same in JS-land.

https://www.npmjs.com/package/openapi-request-validator
https://www.npmjs.com/package/@smartrecruiters/openapi-first
https://www.npmjs.com/package/express-ajv-swagger-validation
https://www.npmjs.com/package/express-openapi-validate
https://www.npmjs.com/package/express-openapi-validator
https://www.npmjs.com/package/openapi-validation-middleware

Some are outdated, some work a bit funny, some have a few bugs, and I feel like we could all be living more fulfilling lives if we collaborated a bit. Maybe time to get https://github.com/openapi-js up and running?

**Comment by Gi60s** [comment]
Looking at your example of https://github.com/Zooz/express-ajv-swagger-validation, it would not be too hard to do this, but I'm not sure if it is any better.

Here is how it could work, using the `openapi-enforcer` without the `openapi-enforcer-middleware`. Note that the below example is functional, but falls short of many of the things that the `openapi-enforcer-middleware` does for you.

**openapi.yml**

```yml
openapi: '3.0.2'
info:
  title: ''
  version: ''
paths:
  /greet:
    get:
      description: Get a generic greeting
      responses:
        200:
          description: Hello, stranger
          content:
            text/plain:
              schema:
                type: string
  /greet/{name}:
    parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
    get:
      description: Get a customized greeting
      responses:
        200:
          description: Hello, whatever name you just put in
          content:
            text/plain:
              schema:
                type: string
```

**server.js**

```js
const express = require('express')
const Enforcer = require('openapi-enforcer')

Enforcer('./openapi.yml')
  .then(enforcer => {
    const app = express()

    function deserializeAndValidateRequest (req, res, next) {
      const [request, error] = enforcer.request({ // get an enforcer request object
        method: req.method,
        path: req.originalUrl
      })
      if (error) {
        res.send(error)
      } else {
        req.enforcerResponse = request.response // store response object so we can use it to validate responses
        req.params = request.path // overwrite express path params with properly serialized values
        // TODO: also copy over headers and query parameters
        next()
      }
    }

    function validateAndSerializeResponse (body, req, res) {
      // validate the response
      const x = req.enforcerResponse(200, body)
      const [response, error] = x

      // handle invalid response
      if (error) {
        res.sendStatus(500)
        console.error(error)

      // send valid response
      } else {
        const { body } = response
        res.send(body)
      }
    }

    app.get('/greet', deserializeAndValidateRequest, (req, res) => {
      // build the response
      const unvalidatedAndUnserializedResponse = 'Hello, stranger'

      // validate the response
      validateAndSerializeResponse(unvalidatedAndUnserializedResponse, req, res)
    })

    app.get('/greet/:name', deserializeAndValidateRequest, (req, res) => {
      // build the response
      const unvalidatedAndUnserializedResponse = 'Hello, ' + req.params.name

      // validate the response
      validateAndSerializeResponse(unvalidatedAndUnserializedResponse, req, res)
    })

    app.listen(3000, () => {
      console.log('listening on port 3000')
    })
  })
```

**Comment by philsturgeon** [comment]
Are you happy with this? It seems not great, it forces the user to still do way too much.

**Comment by Gi60s** [comment]
I agree, it doesn't seem great, and I wouldn't use this code as a model, but more as an illustration of what is possible by using the [`openapi-enforcer`](https://www.npmjs.com/package/openapi-enforcer) package.

The example above is missing a lot of functionality that is contained in the `openapi-enforcer-middleware`, such as:

1. It doesn't deserialize and validate headers, cookies, or query parameters.
2. It doesn't handle invalid request paths and HTTP methods.
3. It doesn't provide 400 responses that tell the client why the request is faulty
4. It doesn't make a safe copy of the request and response objects. The safe copies persist only as long as the context falls within the `openapi-enforcer-middleware` scope. The copy of the request object allows modifying the request object properties and a wrapping for the response send function that runs validation and serialization when `res.send` is called.

The `openapi-enforcer-middleware` even allows you to add your own middleware functions inside of the enforcer's context.

Item 4 above could be solved if I added a function that should be called to restore the context of the request and response objects in case the route wan'ts to call the `next()` function. Something like this:

```js
app.get('/greet/:name', deserializeAndValidateRequest, (req, res, next) => {
  if (req.params.name === 'x') {
    req.restoreContext(next)
  } else {
    // build the response
    const unvalidatedAndUnserializedResponse = 'Hello, ' + req.params.name

    // validate the response
    validateAndSerializeResponse(unvalidatedAndUnserializedResponse, req, res)
  }
})
```

Although it is possible to do everything the `openapi-enforcer-middlware` does using the traditional Express manual routing (instead of using `x-controller` and `x-operation` in your OpenAPI document) it requires that the developer manage more overhead, telling the system when to validate incoming and outgoing requests and when to restore context. It's not hard to do, but it's a lot easier to mess up.

You can repeat the above functionality and do all of the above points using the `openapi-enforcer-middleware` like this:

**openapi.yml**

```yml
openapi: '3.0.2'
info:
  title: ''
  version: ''
x-controller: 'greetings'
paths:
  /greet:
    get:
      x-operation: 'greetStranger'
      description: Get a generic greeting
      responses:
        200:
          description: Hello, stranger
          content:
            text/plain:
              schema:
                type: string
  /greet/{name}:
    parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
    get:
      x-operation: 'greetByName'
      description: Get a customized greeting
      responses:
        200:
          description: Hello, whatever name you just put in
          content:
            text/plain:
              schema:
                type: string
```

**server.js**

```js
const express = require('express')
const Enforcer = require('openapi-enforcer-middleware')

const app = express()

// Create an enforcer middleware instance
const enforcer = Enforcer('openapi.yml')

// Add controller middleware to the enforcer middleware
enforcer.controllers({
  greetings: {
    greetStranger (req, res) {
      res.send('Hello, stranger')
    },
    greetByName (req, res) {
      res.send('Hello, ' + req.params.name)
    }
  }
})
  .catch(console.error)

// Add the enforcer middleware runner to the express app.
app.use(enforcer.middleware())

app.use((err, req, res, next) => {
  console.log(err)
  res.sendStatus(500)
})

// Start the server listening on port 3000.
app.listen(3000, () => {
  console.log('listening on port 3000')
})
```

**Comment by philsturgeon** [comment]
If this middleware validator is suffering from restrictions in the openapi-enforcer package, then maybe they are both past their best. I notice that openapi-enforcer is trying to handle validation entirely by itself and that's a terrifying job which many other people have already solved in JS/TS land. 

Maybe you'd be interested in partnering up with one of those many other middleware developers in JS land, who are getting the job done without needing to write their own invalidator. 

Best of luck with all the things regardless. 👋
