### ISSUE TITLE
Enhancement : add an option to enable/disable responses validation

### ISSUE THREAD

**Issue by jy95** [byu-oit/openapi-enforcer-middleware#23]
Hello,

I think it might be useful to add an option to enable / disable responses validation ( similar to this [option in the previous validator I used](https://github.com/cdimascio/express-openapi-validator#%EF%B8%8F-validateresponses-optional) )

Why ? Whereas it is useful in development environment, it is a performance killer in production.

Thanks in advance

**Comment by Gi60s** [comment]
It is possible to add an option to bypass the validation stage and / or the serialization stage. This functionality does exist in some degree currently using the [schema value](https://byu-oit.github.io/openapi-enforcer/api/components/schema-value/) functionality. You could wrap an entire response in a `schema value` prior to sending to control validation and serialization.

It would also be pretty easy to add an option to the middleware that just did this for you.

**Comment by jy95** [comment]
I think the second second option is better ( `add an option to the middleware` ) ;)

**Comment by Gi60s** [comment]
I've published the feature to npm as version `1.2.0`. You can see the docs for this feature here: https://byu-oit.github.io/openapi-enforcer-middleware/api#openapienforcermiddleware
