### ISSUE TITLE
Dead link in documentation

### ISSUE THREAD

**Issue by jy95** [byu-oit/openapi-enforcer-middleware#26]
Hello,

With my previous issue, I see that explanation about `reqOperationProperty` option is missing : 

![image](https://user-images.githubusercontent.com/9306961/71546255-591a8e80-2995-11ea-8853-d4e5cb460101.png)

The [link](https://github.com/byu-oit/openapi-enforcer/blob/master/docs/components/operation.md) gives me an 404 error

![image](https://user-images.githubusercontent.com/9306961/71546264-75b6c680-2995-11ea-8311-52a0281ee231.png)

**Comment by Gi60s** [comment]
Thank you. The link has now been fixed.
