### ISSUE TITLE
Requiered properties of type String not validated

### ISSUE THREAD

**Issue by MrMoehner** [byu-oit/openapi-enforcer-middleware#32]
Dear Sir or Madam, 

lets said, i am not 100% sure if its my fault;-) but i have noticed the following strange behavior (   Version "openapi-enforcer": "^1.10.5", "openapi-enforcer-middleware": "^1.2.2"):

When defining a schema  with a String property, here "SelectionCount" the content is not checked if there is any content in it or if the content. In my case the field is undefined and i dont see an error in the response. Instead the field is in the response missing. I tried to fill the field in this case with "undefined" as text and got this value also in the response, despite enum and length restrictions. 

    productHeader:
      type: object
      required:
        - SelectionCount
      properties:
        SelectionCount:
          type: string
          minLength: 1
          maxLength: 4
          description: Description.........
          enum:
            - N
            - "1"
            - "2"
            - "3"
            - "4"
            - P
            - X

If i change the property type to "number", it works as expected. Am i missing some information or is this a bug?

Thanks and regards for your Effort

MrMoehner

**Comment by MrMoehner** [comment]
Ok, it was my fault. I have a circular Structure and forgot to list the whole property as "required" for the second level. Unfortunately the middleware doesnt throw an error if there are more properties than in the openapi.yml described. This could be improved, otherwise it works fine!

**Comment by GaryGSC** [comment]
In regards to
> the middleware doesnt throw an error if there are more properties than in the openapi.yml

[`additionalProperties` defaults to `true`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#properties) 🙂
