### ISSUE TITLE
Unexpected extraneous nested errors

### ISSUE THREAD

**Issue by thurt** [byu-oit/openapi-enforcer-middleware#5]
It appears that an error generated by the middleware validation includes a nested error for every aspect of validation, regardless of whether there was actually an error in that aspect or not. For example, I have caused a validation error `In body` yet the error also includes nested exceptions for `In cookie parameters`, `In header parameters`, `In path parameters`, `In query parameters`. 

I expected the error to only include a exception for the `In body` aspect. Is there a good design reason to include all the aspects that I'm not understanding?

The problem I have with the current design is that it becomes extra unnecessary details when I json serialize that error back to the client.

<img width="1169" alt="Screen Shot 2019-04-02 at 4 43 46 PM" src="https://user-images.githubusercontent.com/8955144/55435266-7be35800-5567-11e9-98b4-46a11fb05133.png">

**Comment by thurt** [comment]
I have resolved the primary issue by simply serializing `err.message`

**Comment by Gi60s** [comment]
@thurt You came to the correct conclusion. The error like object that you see there is called an EnforcerException object and it comes from the [openapi-enforcer](https://www.npmjs.com/package/openapi-enforcer) package. You can read up about this object here https://github.com/byu-oit/openapi-enforcer/blob/master/docs/enforcer-exception.md.

Primarily this object is used to track errors within an object hierarchy. You can check at any level in the hierarchy if there really is an error by checking it's `hasException` property.

Thanks for reaching out.
