### ISSUE TITLE
2.0 version not working

### ISSUE THREAD

**Issue by freerider7777** [byu-oit/openapi-enforcer-middleware#57]
Node.js v14.17.3 on Windows 10

package.json
```
    "express": "^4.17.1",
    "openapi-enforcer": "^1.15.4",
    "openapi-enforcer-middleware": "^2.0.0"
```

```
'use strict'
// const { Pool } = require('pg')
const express = require('express')
const Enforcer = require('openapi-enforcer')
const EnforcerMiddleware = require('openapi-enforcer-middleware')

const path = require('path')

const app = express()
// app.use(express.json())

// https://byu-oit.github.io/openapi-enforcer-middleware/2.x/api
const enforcerMiddleware = EnforcerMiddleware(Enforcer('./api.yaml'));
const initOptions = {
    allowOtherQueryParameters: true,
    handleBadRequest: true,
    mockHeader: ''
  }

// add the enforcer middleware runner to the express app
app.use(enforcerMiddleware.init())

// Catch errors
enforcerMiddleware.on('error', err => {
    console.error('Schema errors (processing): ' + err)
    process.exit(1)
  }) 

app.use((req, res, next) => {
    console.log(req);
    console.log('Processing...');
      res.set('Content-Type', 'text/plain')
      res.send({res: 'ok'});
  })

// add error catching middleware
app.use((err, req, res, next) => {
  if (err.statusCode >= 400 && err.statusCode < 500 && err.exception) {
    console.log('some error?')
    res.set('Content-Type', 'text/plain')
    res.status(err.statusCode)
    res.send(err.message)
  } else {
    console.error(err.stack)
    res.sendStatus(err.statusCode || 500)
  }
})

const listener = app.listen(3000, err => {
  if (err) return console.error(err.stack)
  console.log('Server listening on port ' + listener.address().port)
})
```

gives the result on any request:

`Server listening on port 3000
  express:router dispatching GET /pets/1 +7s
  express:router query  : /pets/1 +2ms
  express:router expressInit  : /pets/1 +1ms
  express:router jsonParser  : /pets/1 +1ms
  body-parser:json content-type "application/json" +0ms
  body-parser:json content-encoding "identity" +2ms
  body-parser:json read body +0ms
  body-parser:json parse body +25ms
  body-parser:json parse json +1ms
  express:router <anonymous>  : /pets/1 +2ms
  openapi-enforcer-middleware:init Register request base URL:  +7s
  express:router <anonymous>  : /pets/1 +2ms
  express:router <anonymous>  : /pets/1 +1ms
TypeError: openapi.request is not a function or its return value is not iterable
    at C:\Temp\petstore_generated_server\node_modules\openapi-enforcer-middleware\dist\init.js:78:42
    at Layer.handle [as handle_request] (C:\Temp\petstore_generated_server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Temp\petstore_generated_server\node_modules\express\lib\router\index.js:317:13)
    at C:\Temp\petstore_generated_server\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Temp\petstore_generated_server\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Temp\petstore_generated_server\node_modules\express\lib\router\index.js:275:10)
    at C:\Temp\petstore_generated_server\node_modules\express\node_modules\body-parser\lib\read.js:130:5
    at invokeCallback (C:\Temp\petstore_generated_server\node_modules\express\node_modules\raw-body\index.js:224:16)
    at done (C:\Temp\petstore_generated_server\node_modules\express\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (C:\Temp\petstore_generated_server\node_modules\express\node_modules\raw-body\index.js:273:7)`

**Comment by Gi60s** [comment]
As I looked into this more I realized that the documentation was wrong. We now require the Enforcer to await loading. This is in preparation of the OpenAPI Enforcer v2 library that is in the works. That library will offer greater flexibility in loading, so awaiting may not be necessary, depending on how you're pulling it off.

I've updated the docs. Thank you for the issue.
