### ISSUE TITLE
Issue with Routing after upgrade: How to tell the middlewere, where the controller files are?

### ISSUE THREAD

**Issue by LukasMoehnerBeegy** [byu-oit/openapi-enforcer-middleware#59]
Hello, 

i upgraded from     
"openapi-enforcer": "^1.12.4",
"openapi-enforcer-middleware": "^1.2.2",  

to 

    "openapi-enforcer": "1.15.5",
    "openapi-enforcer-middleware": "2.0.0"

Now i have to following issue in my index.js file. 

VM72 index.js:30 Uncaught TypeError: enforcer.controllers is not a function
    at Object.<anonymous> (VM72 index.js:30)
    at Module._compile (VM50 loader.js:999)
    at Object.Module._extensions..js (VM50 loader.js:1027)
    at Module.load (VM50 loader.js:863)
    at Function.Module._load (VM50 loader.js:708)
    at Function.executeUserEntryPoint [as runMain] (VM71 run_main.js:60)
    at VM45 run_main_module.js:17

 The problem arises in `enforcer.controllers(controllerDirectory).catch(console.error);`
The controller function doesnt exist anymore. 
I tried to change it to the "route" function, but it doesnt work. It says "its not an object"
So the problem is, that i dont know how to tell the middleware, where the controller files are. I played around, but without any succes.

Thanks a lot and regards

MrMoehner

Here is my index.js code.  

`const express = require("express");
const Enforcer = require("openapi-enforcer-middleware");
const path = require("path");
var morgan = require("morgan");
require("dotenv").config();
const controllerDirectory = path.resolve(__dirname, "controllers");
let pathToOpenApiDoc = path.resolve("./OpenApi", "routing.yml");
let enforcer;
const app = express();

// Add HTTP Logging to express, start the logging here
app.use(morgan("dev"));

app.use(express.json());

// Create an enforcer middleware instance
enforcer = Enforcer(pathToOpenApiDoc);
// Add controller middleware to the enforcer middleware, that will also take care of the routing
enforcer.controllers(controllerDirectory).catch(console.error);
// Add the Open API enforcer middleware runner to the express app.
app.use(enforcer.middleware());`

**Comment by Gi60s** [comment]
Thanks for reaching out. There are some significant changes to the middleware v2 release. I also noticed that the README on NPM needs updating, but as for the controllers you will want to use the `route` function instead of the `controllers` function. Here is the documentation for how to use it: https://byu-oit.github.io/openapi-enforcer-middleware/2.x/route-builder

The biggest change is that instead of automatically reading your directory structure it now requires you to import or require them at the top of the file where you are setting up the routes. Then you call the controller's function and pass in any dependencies you have. The biggest reason for this change is to make it more clear how dependencies are passed into controllers.

Within that link I shared you'll probably want to read the section titled **Handling Many Routes**. With your background in knowing how to use v1 of the middleware I think you can skip to that section.

I'll work on updating the readme on NPM to reduce confusion there.

**Comment by LukasMoehnerBeegy** [comment]
Thank you, i have read the documentation, but didnt grasp the idea behind it. Now i am sure i can figure it out.

**Comment by LukasMoehnerBeegy** [comment]
Hey, i finally find time to fix it. Unfortunately https://byu-oit.github.io/openapi-enforcer-middleware/ gives me a 404.

Thanks you!

**Comment by Gi60s** [comment]
Hey Lukas, I know how it can take time to get around to something. The webpage is actually under a new domain now. Try this URL: https://middleware.openapi-enforcer.com/guide/route-builder.html

**Comment by LukasMoehnerBeegy** [comment]
Hello, 

finally finally i was able to take a look at it. 
I totally understand the idea of the change.
After i tried to implement it and in a "maximum call stack exceeded" error i stripped the whole OpenAPI file down to the bare minimum.
Error occurs always at `const enforcer = EnforcerMiddleware(await Enforcer(openapiPath))`


I am basically trying to implement your example now on [https://middleware.openapi-enforcer.com/guide/route-builder.html#how-to-use-the-route-builder](url)
Chapter "Call the Route Builder Middleware".

Now i get the following error with my OpenAPI file, and google is not much help: 
``` 
UnhandledPromiseRejectionWarning: Error: One or more errors exist in the OpenApi definition
  at: paths
    at: /businessunitdatasolar/{businessunitid}
      at: get
        Properties not allowed: **allParameters, parametersMap**
      Property not allowed: methods
```

The openAPI file i am using looks like the one below.  Can you tell me what the error means with **allParameters, parametersMap:**?
Sorry for the format, i tried it with code and everything, but it wont get in formatted
![image](https://user-images.githubusercontent.com/86769342/178146794-5d39f2c3-6312-47b1-b3dd-b9b69b176fef.png)

```
paths:
  /businessunitdatasolar/{businessunitid}:
    x-controller: businessunitdatasolar
    get:
      x-controller: businessunitdatasolar
      x-operation: businessunitdatasolar
      description: Returns all productdata of the given businessunit
      parameters:
        - name: businessunitid
          in: path
          description: ID of businessunit
          required: true
          schema:
            type: string
      responses:
        "200":
          description: All data structured and checked for the given businessunit
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/dataSet"
        "400":
          description: Bad request
        "401":
          description: Authorization information is missing or invalid.
        "5XX":
          description: Unexpected error.
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:
    dataSet:
      type: object
      required:
        - BusinessunitID
      properties:
        BusinessunitID:
          type: string


    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
```

Thanks a lot appreciate it!!!!

**Comment by Gi60s** [comment]
Check out my response to the same problem you're experiencing here: https://github.com/Gi60s/openapi-enforcer-middleware/issues/74#issuecomment-1187779501
