### ISSUE TITLE
using res.json inside controller will fail validation

### ISSUE THREAD

**Issue by thurt** [byu-oit/openapi-enforcer-middleware#6]
I am getting a response validation error when using `res.json({ success: true, message: "Logged out!" })` in my controller. 
```
"Error: Response invalid
  at: body
    Expected a non-null object. Received: "{\"success\":true,\"message\":\"Logged out!\"}""
```
It appears that validation fails because the data is already serialized.

My issue was solved by using `res.send`. 

This makes me wonder if `res.json` should be supported or if it is even worth it considering I could use `res.send` instead?

**Comment by Gi60s** [comment]
Looking at the express response code, specifically the `.json()` and `.jsonp()` functions, those both serialize the body in their own way previous to calling the `res.send` function. That explains why calling those methods produces an error, because the `res.send` is set to validate the value prior to serialization, but it was already serialized by the `json` or `jsonp` functions.

Although it is possible to overwrite those functions, I think the better solution is to just always use `send`.

That said, I'd better document this.

What are your thoughts?

**Comment by Gi60s** [comment]
One thought is I could throw an error message when trying to call `json` or `jsonp` that simply says "Don't call this function while within the enforcer middleware.

**Comment by thurt** [comment]
I haven't used `.jsonp()` before so not sure if leaving that unsupported would limit certain use cases. 

For `.json()`, I discovered at least one use case to consider: when you want to send one of `'STRING', 'NUMBER', 'NULL'` as the json response. The problem here is using `res.send("hi")` will cause `.send` to add `Content-Type` of `text/html`. 

Attempting to manually add `Content-Type` with `res.set({ "Content-Type": "application/json" }).send("hi")` results in invalid json on the client side because the quotes around `"hi"` are not carried over.

For null, like `res.set({ "Content-Type": "application/json" }).send(null)` the `null` is also not carried over to the client (an empty response is also invalid json?).

Attempting the same with a number, like `res.set({ "Content-Type": "application/json" }).send(1)` appears to interpret the `1` as an HTTP status code (I don't see that behavior explained in the 4.x docs but it is in the 3.x docs so it must have been carried over to 4.x).

Fundamentally, `.json()` accepts all the valid json types 
> including object, array, string, Boolean, number, or null

Whereas `.send()` accepts less
> can be a Buffer object, a String, an object, or an Array.

It seems like a rare use case to be sending a single string/number/null for a json response. I think most api developers are sticking with objects/arrays for the flexibility of being able to expand upon the data shape. as a side note: `express.json()` middleware sets the `req.body` to `{}` as the default, so it seems express devs are already assuming your controller code will be working with json objects for the request side of things.

**Comment by Gi60s** [comment]
OK, I've thought about this for a few days.

The openapi-enforcer automatically figures out how to serialize the data. It's better than even the JSON.stringify function because it has the swagger document to tell it what types of data are contained in the fields.

So, I think it makes the most sense to just use `send` and I'll overwrite the `json` function to just call the `send` function.

**Comment by thurt** [comment]
That sounds good.
Although, I'm having continuing issues with `res.send`. For example, when I'm trying to automatically serialize an instance created with sequelize
```
      const message = await Message.create({
        text: req.body.text,
        userId: req.user.id
      });
      res.send({ message });
```
I am getting an unexpected validation error
```
Error: Response invalid
  at: body > message
    Expected a non-null object. Received: [object message]
```

This works with `res.json` before using openapi-enforcer-middleware. Not sure how to go about fixing this

**Comment by thurt** [comment]
There is a `.toJSON()` method available on sequelize instances http://docs.sequelizejs.com/class/lib/model.js~Model.html#instance-method-toJSON
```
      const message = await Message.create({
        text: req.body.text,
        userId: req.user.id
      });
      res.send({ message: message.toJSON() });
```

But it appears to not serialize Date objects included in the instance. I assume that is an issue with the sequelize method specifically

```
Error: Response invalid
  at: body > message
    at: createdAt
      Expected a string. Received: 2019-04-09T06:22:08.575Z
```

**Comment by Gi60s** [comment]
On second thought, as I look at this there is good reason why it requires a plain object. With non plain objects it is not possible to determine if inherited properties are faulty data or if they should be ignored.

I'm not very familiar with sequelize, but you could do this hack:

```js
const message = await Message.create({
  text: req.body.text,
  userId: req.user.id
});
res.send({ message: JSON.parse(message.toJSON()) });
```

For non deeply nested results you could also try and use `Object.assign`

```js
const message = await Message.create({
  text: req.body.text,
  userId: req.user.id
});
res.send({ message: Object.assign({}, message) });
```

**Comment by thurt** [comment]
neither of those suggestions work effectively. 

but this does
```js
const message = await Message.create({
  text: req.body.text,
  userId: req.user.id
});
res.send({ message: JSON.parse(JSON.stringify(message)) });
```

so `JSON.stringify` has some built-in recursive behavior where it will call `.toJSON()` on each sub-object recursively (if the `.toJSON()` method exists). I realize now my Date objects were probably not being serialized because there is no recursion built into just calling `message.toJSON()`.

The issue with `JSON.stringify` is that it also turns the top-level object into a string. So this requires me to subsequently `JSON.parse` so openapi-enforcer-middleware can validate the plain object. 

It seems like we'd need custom data transformer that can behave recursively like `JSON.stringify` but avoid stringifying the top-level object

**Comment by Gi60s** [comment]
Thanks for sharing the solution.

**Comment by thurt** [comment]
Is this something that could be added to openapi-enforcer-middleware so people would not have to `JSON.parse(JSON.stringify(modelInstance))`?

**Comment by Gi60s** [comment]
It's interesting that you ask this. You and I must be of one mind. I've also been thinking about this and I think I can add this functionality, but there are some things to think about.

1. JSON.stringify only serializes properties that are enumerable and are the own property of the object. This means that properties on the prototype are not serialized and there may be cases where that behavior is desired.
2. JSON.stringify does not support circular references which is fine, but using JSON $ref that could be added.

The easiest solution is just to follow the JSON.stringify approach with minor modifications to better support dates and other objects that are not POJOs. This would be a simple fix that I can can work on. To deal with items 1 and 2 above could be a configuration option, but I'm not sure where to put that right now.
