### ISSUE TITLE
Properties not allowed: allParameters, parametersMap

### ISSUE THREAD

**Issue by LukasMoehnerBeegy** [byu-oit/openapi-enforcer-middleware#74]
Hello, 

i am getting the following error 
```
UnhandledPromiseRejectionWarning: Error: One or more errors exist in the OpenApi definition
  at: paths
    at: /test
      at: get
        Properties not allowed: allParameters, parametersMap
      Property not allowed: methods
```

after i updated to new way of handling routes. I basically copied your example here.
https://middleware.openapi-enforcer.com/guide/route-builder.html#handling-many-routes
But i dont think that is the problem. The error occurs already here 

`  const enforcer = EnforcerMiddleware(await Enforcer(openapiPath));`
I just dont understand what is wrong or whtat the error means.

I stripped down my open API File to the most basic as you can see below.
![image](https://user-images.githubusercontent.com/86769342/179519012-977852e2-ce5d-4f95-945d-976bc4961f81.png)

The error still occurs

I am using 
    "openapi-enforcer": "1.12.4",
    "openapi-enforcer-middleware": "1.2.2",

Thanks for your help,appreciate it!

**Comment by Gi60s** [comment]
I have a guess as to what could be going on here. You need to make sure that you're passing either a `string` containing the absolute file path or a plain object that has not already been processed when awaiting the Enforcer. Is the value `openapiPath` an object that has already been processed?

**Comment by Gi60s** [comment]
If you'd like to give me access to read from the repo you're working on I can take a look there too.

**Comment by LukasMoehnerBeegy** [comment]
Hello,

i appreciate your effort. 

I stripped it down to the basic files. 
The error occurs on line 12 of index.js at `  const enforcer = EnforcerMiddleware(await Enforcer(openapiPath));`
Its a string actually, i just checked it.
You can download the repo here 
https://github.com/LukasMoehnerBeegy/Error_open-api-enforcer

Thanks a lot again!!!!

**Comment by Gi60s** [comment]
Unfortunately, it's one of those errors where you might have to smack yourself on the forehead and exclaim "Doh!".

You're looking at the documentation for `openapi-enforcer-middleware` version 2, but you have the  `openapi-enforcer-middleware` version 1 installed.

I cloned your repo, uninstalled version 1, and installed version 2 and it ran as expected.

Good luck and let me know if there is anything else.

**Comment by LukasMoehnerBeegy** [comment]
DOH!. Thanks a lot. I must have run right into the code, instead of checking what am i actually planning to do. Thanks for your time!!!
