### ISSUE TITLE
Support JSON response bodies on validation error(s)

### ISSUE THREAD

**Issue by thurt** [byu-oit/openapi-enforcer-middleware#9]
The default validation error response content-type is a text/html. I am wondering if you have considered adding an option to support JSON response bodies?

use case: I am creating a pure JSON api and I have many application level responses that are other status codes besides 400 that return JSON. I would like the 400 status code responses, which are handled by the middleware, to also be JSON so they could be more easily displayed in a single page application to the end user.

**Comment by Gi60s** [comment]
I believe what you have happening here is that the enforcer is generating an error which it then passes on to the next error handling middleware. If you don't have a custom defined error handling middleware then the Express fallback error handler middleware that runs will generate an HTML document that contains the error message and stack.

In your case you can create a custom error handler middleware that will provide an appropriate JSON response. Here is an example of how that can be done. The custom error handler middleware is near the bottom of the example, right before the server starts to listen.

Also, if the error received by the custom error handler middleware was produced by the enforcer then there will be an `exception` property on the error.

```js
'use strict'
const express = require('express')
const Enforcer = require('openapi-enforcer-middleware')
const path = require('path')
const statuses = require('statuses')

const app = express()
app.use(express.json())

const enforcer = Enforcer(path.resolve(__dirname, 'openapi-v2.yaml'))

// this middleware will handle explicit mock requests
enforcer.mocks(path.resolve(__dirname, 'mock-controllers'), false)
  .catch(console.error)

// this middleware will handle non mock requests
enforcer.controllers(path.resolve(__dirname, 'controllers'))
  .catch(console.error)

// this middleware will automatically run fallback mocks
enforcer.mocks(path.resolve(__dirname, 'mock-controllers'), true)
  .catch(console.error)

// add the enforcer middleware runner to the express app
app.use(enforcer.middleware())

// add custom error handling middleware
app.use((err, req, res, next) => {
  if (err.statusCode >= 400 && err.statusCode < 500 && err.exception) {
    res.status(err.statusCode)
    res.json({
        message: err.message,
        statusCode: err.statusCode
    })
  } else {
    const statusCode = err.statusCode || 500
    console.error(err.stack)
    res.json({
      message: statuses[statusCode],
      statusCode: statusCode 
    })
  }
})

const listener = app.listen(3000, err => {
  if (err) return console.error(err.stack)
  console.log('Server listening on port ' + listener.address().port)
})
```

If this isn't what you're looking for then please continue to comment here, but I'll close this for now.

**Comment by thurt** [comment]
thank you! forgot i could do this 😮
